document/urls.py
from django.urls import path

from .views import (
    add_document,
    list_document,
    edit_document,
    delete_document,
    detail_document,
)

urlpatterns = [
    path("", list_document, name="all_documents"),
    path("add/", add_document, name="add_document"),
    path("<int:pk>/edit/", edit_document, name="edit_document"),
    path("<int:pk>/delete/", delete_document, name="delete_document"),
    path("<int:pk>/", detail_document, name="detail_document"),
]

nsib/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # Folder Url Path
    path("folder/", include("folder.urls")),
    path("document/", include("document.urls")),
    # Userprofiles, departments and account url path
    path("", include("userprofiles.urls")),
    # path("log-out/", views.LogoutView.as_view(), name="log-out"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

document/models.py
from django.db import models
from django.contrib.auth.models import User

from folder.models import Folder
from userprofiles.models import Userprofile


class Document(models.Model):
    name = models.CharField(max_length=255, blank=False, unique=True)
    description = models.CharField(max_length=255)
    upload = models.FileField(max_length=None, upload_to="documents/%Y/%m/%d/")
    folder = models.ForeignKey(Folder, related_name="documents", on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, related_name="documents", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

document/forms.py
from django import forms
from .models import Document
from .models import Folder


class AddDocumentForm(forms.ModelForm):
    name = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={"class": "form-control", "id":"name"})
    )

    description = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={"class": "form-control", "id":"description"})
    )

    folder = forms.ModelChoiceField(queryset=Folder.objects.all(), widget=forms.Select(attrs={"class":"form-control", "id":"folder"}))

    upload = forms.FileField()

    class Meta:
        model = Document
        fields = (
            "name",
            "description",
            "folder",
            "upload",
            # "created_by",
        )
        # widget = {
        #     'file' : forms.FileInput(attrs={'class': 'form-control',
        #                                      'id' : 'input-file'}),
        #     }

document/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from .forms import AddDocumentForm
from .models import Document

# Create your views here.


@login_required(login_url="/")
def list_document(request):
    form = AddDocumentForm()
    if request.user.is_staff:
        documents = Document.objects.all()
    else:
        documents = Document.objects.filter(created_by=request.user)
    context = {
        "documents": documents,
        "form":form
    }
    return render(request, "document/list_document.html", context)


@login_required(login_url="/")
def add_document(request):
    if request.method == "POST":
        form = AddDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.created_by = request.user
            document.save()
            messages.success(request, "document added successfully")
            return redirect("all_folders")
        else:
            messages.error(request, "document not created, try again")
    else:
        form = AddDocumentForm()
    return render(request, "document/add_document.html", {"form": form})


@login_required(login_url="/")
def edit_document(request, pk):
    document = Document.objects.get(created_by=request.user, pk=pk)
    if request.method == "POST":
        form = AddDocumentForm(
            request.POST or None, request.FILES or None, instance=document
        )
        if form.is_valid():
            form.save()

            messages.success(request, "document edited successfully")
            return redirect("dashboard")
        else:
            messages.error(request, "document not edited, try again")
    else:
        form = AddDocumentForm(instance=document)
    return render(request, "document/add_document.html", {"form": form})


@login_required(login_url="/")
def detail_document(request, pk):
    document = Document.objects.get(created_by=request.user, pk=pk)
    return render(request, "document/detail_document.html", {"document": document})


@login_required(login_url="/")
def delete_document(request, pk):
    document = Document.objects.get(created_by=request.user, pk=pk)
    document.delete()
    return redirect("list_document")

document/templates/document/add_document.html
{% extends 'userprofiles/dashboard_temp.html' %} {% block content %}

<div class="container mt-5 mb-5">
  <div class="row mt-5">
    <div class="col-5">
      <form method="POST" enctype= "multipart/form-data">
        {% csrf_token %} 
        
        {{form.as_p}}

        <input type="submit" value="Upload Document" class="btn btn-primary" />
      </form>
    </div>
  </div>
</div>
{% endblock content %}

document/templates/document/detail_document.html
{% extends 'userprofiles/dashboard_temp.html' %} {% block content %}
<style>
  #myDoc {
    width: 450px;
    height: 700px;
  }
</style>
<div class="container mt-5 mb-5">
  <div class="row mt-5">
    <div class="col-8">
      {% if document %}
      {{document.created_by}} 
      <iframe src="{{document.upload.url}}" framerborder="0" height="500" width="800" ></iframe>
      {{document.name}} 
      
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

document/templates/document/list_document.html
{% extends 'userprofiles/dashboard_temp.html' %} 

{% block title %}
Documents
{% endblock %}

{% block content %}
<div>
  <div class="mt-5 d-flex justify-content-end">
    <div></div>
    <div>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add Document
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Document</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'add_document' %}" method="POST">
            <div class="modal-body">
              {% csrf_token %} 
                {{form.as_p}}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!--          -->
      <!-- Modal -->
      <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Edit Document</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'add_document' %}" method="POST">
            <div class="modal-body">
              {% csrf_token %} 
              <input type="hidden" class="form-control" name="id" id="id" />
                {{form.as_p}}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Update Document</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% if documents %}
  <div class="my-2 mt-5">
    <h4 class="text-md-start">Documents</h4>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Folder</th>
          <th scope="col">Created By</th>
          <th scope="col">Created At</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Folder</th>
          <th scope="col">Created By</th>
          <th scope="col">Created At</th>
          <th scope="col">Action</th>
        </tr>
      </tfoot>
      <tbody>
        {% for document in documents %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{document.name}}</td>
          <td>{{document.description}}</td>
          <td>{{document.folder.name}}</td>
          <td>{{document.created_by}}</td>
          <td>{{document.created_at}}</td>
          <td>
            <a class="btn btn-warning btn-sm" href="#">View</a>
            
            <button type="button" class="btn btn-primary btn-sm"
              data-bs-toggle="modal" 
              data-bs-target="#editModal" 
              data-bs-id="{{document.id}}"
              data-bs-name="{{document.name}}"
              data-bs-description="{{document.description}}"
              data-bs-folder="{{document.folder.id}}"
              data-bs-upload="{{document.upload}}"
              data-bs-department="{{document.department}}"
              >
              Edit
            </button>
            <a class="btn btn-danger btn-sm" href="{% url 'delete_document' document.id %}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p class="my-5">You have not created any document!</p>

    {% endif %}
  </div>
</div>

{% endblock content %}


{% block script %}
<script>
  const editModal = document.getElementById('editModal')
  editModal.addEventListener('show.bs.modal', event => {
    // Button that triggered the modal
    const button = event.relatedTarget
    
    // Extract info from data-bs-* attributes
    const document_id = button.getAttribute('data-bs-id')
    const document_name = button.getAttribute('data-bs-name')
    const document_description = button.getAttribute('data-bs-description')
    var document_folder = button.getAttribute('data-bs-folder')
    const document_upload = button.getAttribute('data-bs-upload')
    
    const documentId = editModal.querySelector('#id')
    const documentName = editModal.querySelector('#name')
    const documentDescription = editModal.querySelector('#description')
    const documentFolder = editModal.querySelector('#folder')
    const documentUpload = editModal.querySelector('#id_upload')
    
    documentId.value = document_id
    documentName.value = document_name
    documentDescription.value = document_description
    documentFolder.value = document_folder
    // documentUpload.value = document_upload
  })
</script>
{% endblock %}